### ISSUE TITLE
Tags Graph did not show each scenario when tags are only put on Scenario Outline Examples. 

### ISSUE THREAD

**Issue by bcub** [damianszczepanik/cucumber-reporting#174]
Hello,

I 've just checked with last release version (0.3.1), this bug seems to occured when  I put tags on Scenario Outline Examples.
Check screenshot:

In the feature file, there is 15 test scenario, 6 scenario outline with 2  differents Examples, and one with  3 example.
![cucumber jvm html reports feature](https://cloud.githubusercontent.com/assets/14070722/9600530/daad6378-509b-11e5-822d-a564b4cc4347.png)

Here we can see that only one are counted in @CS tags whereas there was 8. (7 that succeed and one that failed)
![cucumber jvm html reports tag overview](https://cloud.githubusercontent.com/assets/14070722/9600417/46363f6c-509b-11e5-8a18-4e6ff99c3994.png)

Regards,

bcube

**Comment by damianszczepanik** [comment]
Looks like something that should be fixed. Can you share json file that allows me to reproduce the issue?

**Comment by bcub** [comment]
You wil find here a json file where the bug occurred, it's not the same file but it's still occuring.

You wil find it here:
https://gist.github.com/bcub/a7ab8ed3a2f20a0d0d0c

Thanks for you quick answer!

**Comment by bcub** [comment]
I've tried to put global tags for the Feature, and then the tags are well displayed and counted.

**Comment by damianszczepanik** [comment]
Problem is solved. I have eliminated part of passed file which is useless and left only the part that causes problem:
```
[
  {
    "id": "selector",
    "description": "",
    "name": "Tires Selector",
    "keyword": "Feature",
    "line": 1,
    "elements": [
      {
        "id": "selector;ts-dimension-search;;2",
        "tags": [
          {
            "name": "@US",
            "line": 62
          }
        ],
        "description": "",
        "name": "TS dimension search",
        "keyword": "Scenario Outline",
        "line": 65,
        "steps": [
        ],
        "type": "scenario"
      },
      {
        "id": "selector;ts-dimension-search;;2",
        "tags": [
          {
            "name": "@CS",
            "line": 67
          }
        ],
        "description": "",
        "name": "TS dimension search",
        "keyword": "Scenario Outline",
        "line": 70,
        "steps": [
        ],
        "type": "scenario"
      }
    ],
    "uri": "bdd/TS/TSTester.feature"
  }
]
```

And the problem is that two steps have the same ID. I've checked other json files and the id should be unique. Looks like the problem with cucumber itself than cucumber plugin.

I recommend to upgrade cucumber to the most recent version and it this does not help - raise the issue on gihub project.
